### ISSUE TITLE
Printer in bootloop - "machine start up in progress"

### ISSUE THREAD

**Issue by akkut** [CrealityOfficial/Ender-3_V3_KE_Annex#3]
Hello,

I have a problem my printer isn't booting correct and I'm not able to connect via SSH.
The display only shows "machine start up in progress". I installed fluidd a few days ago
and it worked great. The webinterface gives me this infos: 

![klippy not connected](https://github.com/CrealityOfficial/Ender-3_V3_KE_Annex/assets/126557097/b788f81d-15b9-435d-a00b-9e77542d5930)

my update status is this one: 

![update status](https://github.com/CrealityOfficial/Ender-3_V3_KE_Annex/assets/126557097/ef9e693d-cd4b-4568-af50-248a4a8133a0)

and I can't create a log for klippy. I get an error that the log can't be created.
Restarting klipper is also not working.
I attached a moonraker log. 

[moonraker.log](https://github.com/CrealityOfficial/Ender-3_V3_KE_Annex/files/14143230/moonraker.log)

Does someone have an idea how to reset the printer or how I could get it out of the bootloop?

Additional info: I can reach the printer via OrcaPrint and the creality webinterface but I can't make any changes.

Thanks, 
akkut

**Comment by PPAC37** [comment]
Hi !

For me, it was especially important not to update Klipper as offered by Fluidd. Because the original Klippy on CrealityOS is a version tweaked by Creality.

And unfortunately, now, for me, you are good to do a reset, or recovery, of the firmware of the machine.

Fortunately the K1 reset method on https://github.com/Guilouz/Creality-K1-and-K1-Max/wiki/Reset-Factory-Settings seems to work for the KE, so you may dont have to do the firmware recovery https://github.com/CrealityOfficial/Ender-3_V3_KE_Annex/tree/main/firmware%20recovery%20tool

Good reset.

**Comment by akkut** [comment]
Hi PPAC37,

first thanks for the quick answer and the help! The K1 reset seems to work like a charm.
How can I tell Fluidd to not update automatically?

**Comment by PPAC37** [comment]
I don't really know how you can tell Fluidd to not update automatically.

Because I mostly use mainsail. 
And currently, my Fluidd does not offer me a Klipper update. (I did a reset not long ago to see if the K1 reset method worked with the KE)

But befor the reset, when I had Fluidd that offer me to update Klipper, it seemed to me that fluidd asks before updating. So for me, you just have to say : no, do not update Klipper, and then look in the fluidd notification settings to no longer display when there is a Klipper update available.

**Comment by akkut** [comment]
Okay I will keep my eyes open and thanks again you saved me from a big headache!

**Comment by PPAC37** [comment]
No problem, it is especially @Guilouz who must be thanked for having provided this reset method for the K1 / K1 Max, which luckily is compatible with the KE.

Otherwise, even if your specific problem is solved, I tell myself that we should probably make a new issue on the repository which explains that if we update Klipper via fluidd, this  destabilizes the Creality OS boot process. (Or leave this issue open for the next person who has the problem.)

**Comment by akkut** [comment]
Good idea, I will reopen this issue for now.

**Comment by akkut** [comment]
After a few days of testing, I think I found out why the printer was doing software updates.
If you only install fluidd and make it so you can use third party webcams there is no software update option in the settings!

Which lets me to believe that installing OctoEverywhere was responsible for the software updates!
